version: "3.9"
   
services:
  tab_music:
    build: ${MUSIC_BUILD_TARGET}
    environment:
      # BigQuery variables
      - GOOGLE_APPLICATION_CREDENTIALS=${GOOGLE_APPLICATION_CREDENTIALS}
      - PROJECT_ID=${PROJECT_ID}
      - DATASET_LATEST_ID=${DATASET_LATEST_ID}
      - TABLE_MUSIC_ID=${TABLE_MUSIC_ID}
      # Bind mount targets
      - LOGS_TARGET=${LOGS_TARGET}
      - LIBRARY_TARGET=${LIBRARY_TARGET}
      - REPORT_TARGET=${REPORT_TARGET}
    volumes:
      # Logging
      - type: bind
        source: ${LOGS_SOURCE}
        target: ${LOGS_TARGET}
        read_only: ${LOGS_TARGET_RO}
      # BigQuery Credentials
      - type: bind
        source: ${BQ_SOURCE}
        target: ${GOOGLE_APPLICATION_CREDENTIALS}
        read_only: ${BQ_RO}
      # Library
      - type: bind
        source: ${LIBRARY_SOURCE}
        target: ${LIBRARY_TARGET}
        read_only: ${LIBRARY_TARGET_RO}
      # Host Report Save Directory
      - type: bind
        source: ${REPORT_SOURCE}
        target: ${REPORT_TARGET}
        read_only: ${REPORT_RO}

      